name: Clock_in

on:
  schedule:
    # 每天早上6点半触发任务，对应UTC时间的22:30
    - cron: '30 22 * * *'
  workflow_dispatch:

jobs:
  Clock_in:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install packages 
        run: pip3 install -r requirements.txt

      - name: Run the script
        env:
          XUHAO: ${{ secrets.XUHAO }}
          SEATNO: ${{ secrets.SEATNO }}
          MIMA: ${{ secrets.MIMA }}
          PUSHPLUS: ${{ secrets.PUSHPLUS }}
        run: python clockIn_lib.py
